#! /bin/sh

### AUTOSTARTS ###
killall sxhkd
killall nitrogen
killall polybar
killall picom

setxkbmap is
sxhkd &
nitrogen --restore &
polybar bar1 &
picom --experimental-backend &

### MONITOR WORKSPACES ###
bspc monitor -d dev www dis mus gam oth 

### CONFIG ###
bspc config border_width         4
bspc config window_gap           12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config normal_border_color  "#181818"
bspc config focused_border_color "#0586ff"

bspc config automatic_scheme tall

bspc rule -a Gimp state=floating follow=on

bspc rule -a firefox desktop=^2 focus=on follow=on
bspc rule -a Steam   desktop=^5 focus=on follow=on
